Document: parcellite
Title: Debian parcellite Manual
Author: <insert document author here>
Abstract: This manual describes what parcellite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/parcellite/parcellite.sgml.gz

Format: postscript
Files: /usr/share/doc/parcellite/parcellite.ps.gz

Format: text
Files: /usr/share/doc/parcellite/parcellite.text.gz

Format: HTML
Index: /usr/share/doc/parcellite/html/index.html
Files: /usr/share/doc/parcellite/html/*.html
